# Generated by Django 3.2 on 2023-01-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_title_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='reviews',
        ),
    ]
